version: '3.8'

services:
  database:
    image: postgres
    container_name: postgres000db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: laravel_wordpress_docker
    volumes:
      - ./postgres-data:/var/lib/postgressql/data
    ports:
      - '5432:5432'
  php-apache:
    container_name: php-apache
    build:
      context: ./php
    ports:
        - '8080:80'
    volumes:
      - ./src:/var/www/laravel_docker
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - database